Feature/init model
chenejac/TeslaRIS-backend pull request #45
Opened 2023-04-13 11:37 UTC by ivanmrsulja

Implemented model as is specified in [puml class diagram](https://github.com/chenejac/TeslaRIS-backend/blob/feature/docs/docs/model.puml).

Implemented JPA repositories for every entity.

2023-04-15 09:38 UTC, chenejac requested changes
@milospp, @ivanmrsulja well done. A couple of comments:

- I think we should be less rigorous what is mandatory at model level, because there can be always some exceptions. For instance, some dates (from, to) should be defined, but there might be that the user who is cataloguing doesn't know that information. In that case, the provided information still can be useful for CRIS (TeslaRIS). For instance, some researcher participated in a project, but there is no information in which time-frame. 
- @ivanmrsulja mentioned last time that MultilingualContent should use EAGER loading, not sure is that still valid. If that is necessary, we can keep that. If not, I suggested in my comment which peace of information should use EAGER, and which LAZY loading. Namely, we might have simple and full record editing (it is implemented in the CRIS UNS). For instance, abstract/description is in the full record editing which is rarely used, therefore abstract/description might use LAZY loading
- BaseEntity might be enriched with adminNote, createdBy, last_modification, modifiedBy. Why Sequence strategy is used instead of Identity for ID generation?

2023-04-15 09:39 UTC, chenejac requested changes
@milospp, @ivanmrsulja well done. A couple of comments:

- I think we should be less rigorous what is mandatory at model level, because there can be always some exceptions. For instance, some dates (from, to) should be defined, but there might be that the user who is cataloguing doesn't know that information. In that case, the provided information still can be useful for CRIS (TeslaRIS). For instance, some researcher participated in a project, but there is no information in which time-frame. 
- @ivanmrsulja mentioned last time that MultilingualContent should use EAGER loading, not sure is that still valid. If that is necessary, we can keep that. If not, I suggested in my comment which peace of information should use EAGER, and which LAZY loading. Namely, we might have simple and full record editing (it is implemented in the CRIS UNS). For instance, abstract/description is in the full record editing which is rarely used, therefore abstract/description might use LAZY loading
- BaseEntity might be enriched with adminNote, createdBy, last_modification, modifiedBy. Why Sequence strategy is used instead of Identity for ID generation?

2023-04-17 11:22 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/AffiliationStatement.java
> +    @JoinColumn(name = "address_id")
Yes, this will work. Just tested

2023-04-17 11:30 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/Document.java
> +    @Column(name = "admin_note", nullable = false)
adminNote is moved to Base Entity next to createdAt/By, updatedAt/By attributes. 
but _Set<MultiLingualContent> note;_ I would leave it as is in the Document

2023-04-17 12:01 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/MonographPublication.java
> +}
Nullable true or false?

2023-04-17 12:01 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/JournalPublication.java
> +}
Nullable true or false?

2023-04-17 12:01 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/ProceedingsPublication.java
> +}
Nullable true or false?

2023-04-17 12:17 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/Monograph.java
> +    ResearchArea researchArea;
Nullable true or false?

2023-04-17 12:21 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/Journal.java
> +    Set<MultiLingualContent> nameAbbreviation;
nameAbbreviation should be LAZY then?

2023-04-17 12:22 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/Journal.java
> +    Set<MultiLingualContent> nameAbbreviation;
Added
```
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    Set<MultiLingualContent> title;
```

2023-04-17 12:25 UTC, milospp commented on src/main/java/rs/teslaris/core/model/institution/OrganisationUnit.java
> +    String acronym;
Should the nameAbbreviation (acronym) be a String or MultiLingualContent

2023-04-17 12:33 UTC, milospp commented on src/main/java/rs/teslaris/core/model/person/Education.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Should it be Lazy?

2023-04-17 12:35 UTC, milospp commented on src/main/java/rs/teslaris/core/model/person/Employment.java
> +//    Position position; // TODO: ADD NECESSARY CLASS WITH FIELDS
SCIENTIFIC_ADVISOR,
    ASSISTANT_TRAINEE,
    EXPERT_ASSOCIATE,
    ASSISTANT,
    SENIOR_EXPERT_ASSOCIATE,
    INSTRUCTOR,
    EXPERT_ADVISOR,
    COLLABORATOR,
    SENIOR_INSTRUCTOR,
    TEACHER,
    TEACHER_OF_FOREIGN_LANGUAGES_AND_SKILLS,
    RESEARCHER,
    PROFESSOR_ENGINEER_HABILITATED,
    ASSISTANT_WITH_MASTER,
    ASSISTANT_WITH_MAGISTRATE,
    ASSISTANT_WITH_DOCTORATE,
    LECTURER,
    SENIOR_LECTURER,
    PROFESSOR_OF_VOCATIONAL_STUDIES,
    ASSISTANT_PROFESSOR,
    ASSOCIATE_PROFESSOR,
    TEACHING_ASSISTANT,
    FULL_PROFESSOR,
    PROFESSOR_EMERITUS,
    RETIRED_PROFESSOR,
    RESEARCH_TRAINEE,
    RESEARCH_ASSOCIATE,
    SCIENTIFIC_COLLABORATOR,
    SENIOR_SCIENTIFIC_COLLABORATOR,

2023-04-17 12:51 UTC, milospp commented on src/main/java/rs/teslaris/core/model/person/PersonalInfo.java
> +    PostalAddress postalAddress;
Just found out that we nowhere use the PersonalInfo class?

2023-04-17 13:47 UTC, milospp commented on src/main/java/rs/teslaris/core/model/project/ProjectDocument.java
> +    @ManyToOne(fetch = FetchType.LAZY)
`    @ManyToOne(fetch = FetchType.LAZY, optional = false)
`

2023-04-17 13:52 UTC, milospp commented on src/main/java/rs/teslaris/core/model/document/Document.java
> +    @Column(name = "admin_note", nullable = false)
Edit: Removed note from the Document class because it has the same purpose as adminNote in BaseEntity

2023-04-17 13:54 UTC, milospp commented on src/main/java/rs/teslaris/core/model/person/Involvement.java
> +    @JoinColumn(name = "organisation_unit_id")
Added default `nullable = true` into param as a reminder

2023-04-18 08:25 UTC, chenejac requested changes
@milospp I have responded to your comments/questions

2023-04-18 08:25 UTC, chenejac commented on src/main/java/rs/teslaris/core/model/document/Journal.java
> +    Set<MultiLingualContent> nameAbbreviation;
no, please return nameAbbreviation to be Eager, it is more used than title

2023-04-18 08:25 UTC, chenejac commented on src/main/java/rs/teslaris/core/model/document/JournalPublication.java
> +}
nullable false, it will be research_article by default (in 90+ % it is research article, it can be specified as default option in UI)

2023-04-18 08:25 UTC, chenejac commented on src/main/java/rs/teslaris/core/model/document/Monograph.java
> +    ResearchArea researchArea;
nullable false (RESEARCH_MONOGRAPH by default)

2023-04-18 08:25 UTC, chenejac commented on src/main/java/rs/teslaris/core/model/document/ProceedingsPublication.java
> +}
nullable false (REGULAR_FULL_ARTICLE by default)

2023-04-18 08:25 UTC, chenejac commented on src/main/java/rs/teslaris/core/model/person/PersonalInfo.java
> +    PostalAddress postalAddress;
PersonalInfo should be embedded in Person I believe

2023-04-19 11:42 UTC, milospp commented on src/main/java/rs/teslaris/core/model/person/Education.java
> +    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Changed back to EAGER

2023-04-20 11:26 UTC, chenejac approved these changes
@ivanmrsulja @milospp let's merge this in the current form. It is good enough for this phase, although I am quite sure it will be modified (at least slightly) later.

2023-04-20 11:26 UTC, merged