Feature/person crud
chenejac/TeslaRIS-backend pull request #47
Opened 2023-05-04 19:02 UTC by ivanmrsulja

## Description

Added CRUD operations for Person and Involvement entities.

## How should this be tested?

These functionalities can be tested by running unit tests and through API testing tool like postman or cURL.

## Checklist

-   [ ] I have tested these changes locally
-   [ ] I have added tests that cover these changes (if applicable)
-   [ ] I have updated the documentation (if applicable)
-   [ ] I have added or updated the necessary comments in the code

2023-05-08 12:23 UTC, chenejac requested changes
@ivanmrsulja thanks for this. Please check my comments.

2023-05-09 13:48 UTC, ivanmrsulja commented on src/main/java/rs/teslaris/core/service/impl/PersonIndexServiceImpl.java
> +    private final ElasticsearchOperations template;
I have renamed it as you advised.

2023-05-09 13:49 UTC, ivanmrsulja commented on src/main/java/rs/teslaris/core/service/LanguageTagService.java
> +    LanguageTag findLanguageTagById(Integer languageTagId);
As we discussed, it can be easily added later, however, I can add it now if you prefer it like that 😀

2023-05-09 14:04 UTC, ivanmrsulja commented on src/main/java/rs/teslaris/core/aspect/PersonEditCheckAspect.java
> +            case "AUTHOR":
I have added an enum as you advised.

2023-05-09 14:06 UTC, ivanmrsulja commented on src/main/java/rs/teslaris/core/controller/InvolvementController.java
> +    private final InvolvementToInvolvementDTO involvementToInvolvementDTO;
I have redefined every conversion method as static

2023-05-09 16:31 UTC, ivanmrsulja commented
I have implemented the improvements you suggested.

2023-05-11 10:44 UTC, chenejac approved these changes
@ivanmrsulja thanks

2023-05-11 10:44 UTC, merged